@host = http://localhost:5169
POST {{host}}/Account/register

Content-Type: application/json

{
  "firstName": "string",
  "lastName": "string",
  "phoneNember": "string",
  "email": "user@example.com",
  "password": "string",
  "confirmPassword": "string",
  "gender": 0,
  "dateOfBirth": "2023-12-10T01:02:44.361Z"
}

