@host = http://localhost:5169
POST {{host}}/auth/register
Content-Type: application/json
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0

{
    "FirstName": "Admin2",
    "LastName": "Admin",
    "email": "admin@localhost",
    "password": "admin"
}

